### ISSUE TITLE
input.json example

### ISSUE THREAD

**Issue by ghost** [kbaum/highchart-image-api#1]
Would be nice to see a input.json example code...

**Comment by kbaum** [comment]
Is this what you're looking for?

http://vts-temp.s3.amazonaws.com/kevinreedyhighchartimageapi_20140216_064700.jpg

**Comment by ghost** [comment]
Yes.
Very sorry for this sir.

**Comment by kbaum** [comment]
No problem!—

**Comment by ghost** [comment]
Just one more thing if you please, ...how can I avoid creating those extra .json and .png files? I'm using the HTTParty call method.
Thanks!

**Comment by kbaum** [comment]
@hugobento Not sure what you mean by extra .json and .png files.  The json file is the input to the api and the png is the chart that's produced.

**Comment by ghost** [comment]
Ok I got it. It's a little odd but ok. If I may explain:
- While the API is running: calling the api generates two extra files, a bar_chartXXXXXX.png and a infileXXXXX.json on the /tmp folder (which was the one I was outputting too).
- When I stop the API, all these 2 extra files are removed from /tmp
